@startmindmap

* 实现领域驱动设计
** 背景
*** 设计不只是感观,设计就是产品的工作方式。 --Steve Jobs
*** 为什么需要DDD？
**** DDD的好处
***** 软件开发的最大问题之一便是业务人员和技术人员需要某种翻译才能交流。DDD将业务人员和技术人员放在同一个层面上。
** 目的
*** 创造一个可测试的、可伸缩的、组织良好的软件模型。
** 内容
*** 挑战
**** TODO
*** 概念
**** 战略、战术设计
***** TODO
**** 战略设计基础： 领域、子域和限界上下文
***** 领域
****** 一个组织所做的事情以及其中所包含的一切
****** 一个领域被分为若干子域，领域模型在限界上下文中完成开发
****** 在开发一个领域模型时，我们关注的通常只是这个业务系统的某个方面
***** 子域
****** 核心域： 业务成功的主要促成因素
****** 支撑子域： 限界上下文对应着业务的某些重要方面，但却不是核心。创建支撑子域的原因在于它们专注于业务的某个方面。
****** 通用子域： 被用于整个业务系统的子域。
***** 限界上下文
****** 上下文命名方式： 模型名+上下文。比如协作上下文、身份与访问上下文
****** 同一事物，在不同阶段可能拥有不同概念，比如图书出版前中后阶段，图书定义不同，所以其各自拥有限界上下文
***** 问题空间、解决方案空间
****** 问题空间： 划分子域
****** 解决方案空间： 划分限界上下文
***** 常见问题
****** 贫血模型： 业务逻辑不包含任何业务行为，数据与业务行为不一致
****** 谷仓效应： 同一模型在不同上下文中各自建模，相似但不一致，难以复用和对齐
***** case
****** <img:./image/2026-01-06-19-13-20.png{scale=0.1}>
****** <img:./image/2026-01-06-19-18-58.png{scale=0.1}>
****** <img:./image/2026-01-06-19-19-45.png{scale=0.1}>
****** <img:./image/2026-01-06-19-40-04.png{scale=0.1}>
**** 上下文映射图
**** 架构
***** 分层架构
***** 六边形架构
***** 面向服务架构
**** 实体
***** 为什么要避免大范围使用实体？
**** 值对象
***** 如何将实体聚合为不变的整体？
***** 持久化会带来什么不利影响？
**** 领域服务
***** 领域是否是有状态的？
***** 什么时候使用领域服务？
***** 如何设计领域服务？
**** 领域事件
***** 命名方式： 名词+动词组合
***** 领域事件与事件机制的区别是什么？
***** 如何创建发布订阅机制？
***** 消息机制带来的挑战有哪些？
**** 模块
***** 如何保障不同对象之间只存在有限耦合？
**** 聚合
***** 不同小规模对象集群如何聚合，以实现创建一致性边界？
**** 工厂
***** 多租户环境是什么？可能会存在什么问题？
**** 资源库
***** 和数据库的区别是什么？
**** 集成限界上下文
***** 如何通过上下文映射图集成不同模型？
**** 应用程序
***** 客户应该如何使用模型？
**** 其他
***** 什么是对象-关系阻抗失配？
*** 实践
**** 如何在项目中应用DDD
**** 如何做模型分离

@endmindmap
